Este notebook tem como objetivo inspecionar a tabela e dicionario, criar as features necessárias e a estatística descritiva.

In [0]:
%sql

SELECT * FROM sandbox.prcg.transacoes LIMIT 5

datahora_entregue,duracao,distancia,vlr_pago,id_motorista,latitude_origem,longitude_origem,latitude_destino,longitude_destino
03/11/2025 07:12,12,4.2,23.97,1,-23.513742609587695,-46.62327810242303,-23.483853341186528,-46.648585835169115
23/10/2025 09:43,11,4.3,24.71,2,-23.51207921873963,-46.62739562527016,-23.474032512968865,-46.63578672625711
22/10/2025 11:12,9,4.2,23.01,1,-23.574913898123835,-46.60181176389887,-23.611927332177384,-46.592856334210495
18/10/2025 18:03,11,3.4,21.2,3,-23.581033986174024,-46.63696302378459,-23.598154937550955,-46.66461159876348
13/10/2025 11:54,11,3.6,21.74,3,-23.581544813632622,-46.643830193209304,-23.56791182574625,-46.611816490410796

In [0]:
%sql
WITH tbl_features AS (
  SELECT 
    day(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as dia,
    dayofweek(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as dia_semana,
    month(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as mes,
    hour(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as hora,
    duracao,
    distancia,
    vlr_pago,
    latitude_origem,
    longitude_origem,
    latitude_destino,
    longitude_destino
  FROM sandbox.prcg.transacoes
)
SELECT 
  dia,
  dia_semana,
  mes,
  hora,
  case when hora < 12 and hora > 6 then 1
       when hora >= 12 and hora <= 18 then 2
       else 3 end as periodo,
  duracao,
  distancia,
  vlr_pago,
  latitude_origem,
  longitude_origem,
  latitude_destino,
  longitude_destino
FROM tbl_features

dia,dia_semana,mes,hora,periodo,duracao,distancia,vlr_pago,latitude_origem,longitude_origem,latitude_destino,longitude_destino
3,2,11,7,1,12,4.2,23.97,-23.513742609587695,-46.62327810242303,-23.483853341186528,-46.648585835169115
23,5,10,9,1,11,4.3,24.71,-23.51207921873963,-46.62739562527016,-23.474032512968865,-46.63578672625711
22,4,10,11,1,9,4.2,23.01,-23.574913898123835,-46.60181176389887,-23.611927332177384,-46.592856334210495
18,7,10,18,2,11,3.4,21.2,-23.581033986174024,-46.63696302378459,-23.598154937550955,-46.66461159876348
13,2,10,11,1,11,3.6,21.74,-23.581544813632622,-46.643830193209304,-23.56791182574625,-46.611816490410796
11,7,10,11,1,8,3.8,23.26,-23.52960821981363,-46.66281396280993,-23.499799594780598,-46.64438846657277
11,7,10,8,1,9,4.2,24.74,-23.585069168120537,-46.61634743301252,-23.621745269018117,-46.62681068452422
10,6,10,19,3,106,4.9,27.0,-23.542660608006138,-46.680536511354774,-23.499054094285043,-46.68864739163299
10,6,10,18,2,15,5.1,27.82,-23.595103808176866,-46.64581113130338,-23.587440347311027,-46.59654247057943
7,3,10,11,1,9,3.4,20.71,-23.56826141657061,-46.660487972079046,-23.58510671249467,-46.68833247475998
27,7,9,14,2,10,3.7,23.42,-23.578294153238105,-46.6534508039132,-23.55193164669454,-46.675712767513154
27,7,9,12,2,6,2.1,16.2,-23.531923629943602,-46.629294258551305,-23.54700975633346,-46.61683563576386
23,3,9,10,1,10,4.1,23.4,-23.58697496231883,-46.62632213376367,-23.604073256923634,-46.66195040152131
19,6,9,9,1,11,3.7,21.92,-23.52947076336354,-46.60517167399793,-23.557731427127635,-46.58584665434615
18,5,9,13,2,17,4.2,24.82,-23.526962125058105,-46.66554264954448,-23.497083690110916,-46.64021742405368
16,3,9,14,2,12,4.7,26.08,-23.558598298015358,-46.67850203387555,-23.57886384844989,-46.63805202371573
13,7,9,17,2,8,2.2,17.67,-23.54163753364745,-46.614037768125336,-23.52253115268579,-46.60814347510885
13,7,9,16,2,11,3.0,21.11,-23.557645143389077,-46.66165842109194,-23.535340013539198,-46.678329404076436
12,6,9,14,2,16,2.5,16.82,-23.528048184340392,-46.63099403686923,-23.508023091074815,-46.61969599255575
8,2,9,16,2,11,4.5,24.85,-23.566733829582645,-46.67372485621996,-23.529274511914664,-46.65665299357462
3,4,9,10,1,6,1.7,16.18,-23.53833649152686,-46.643437197567046,-23.536724582097786,-46.65999351890625
1,2,9,15,2,8,4.0,22.53,-23.56957254520901,-46.66659433864864,-23.593493812011083,-46.6372360576488
28,5,8,17,2,7,2.8,18.36,-23.541157422922325,-46.607837156664694,-23.520586676303246,-46.59189699759486
27,4,8,12,2,14,5.1,27.52,-23.588772848101467,-46.6611220545302,-23.62730770190184,-46.688479723115364
26,3,8,12,2,13,4.6,25.51,-23.584460252521968,-46.60733785953872,-23.54401601468928,-46.61759267129255
18,2,8,17,2,26,4.2,24.12,-23.514788383564063,-46.6195319362893,-23.511689766578304,-46.66051815398106
14,5,8,15,2,9,3.9,22.12,-23.58207736884028,-46.650260903436156,-23.56285840555449,-46.68227265070954
13,4,8,13,2,13,4.3,24.72,-23.589245312520834,-46.63633348551772,-23.617378767243768,-46.66536855123951
11,2,8,8,1,6,2.2,15.96,-23.5320030138356,-46.62551037679862,-23.513511570232943,-46.633379988543886
8,6,8,15,2,8,4.2,23.5,-23.512599872644785,-46.63379235196191,-23.48310833839403,-46.65964266895046
8,6,8,14,2,8,3.5,21.05,-23.576015220388545,-46.65356715035511,-23.544455636343592,-46.65178816114695
8,6,8,11,1,6,1.8,14.34,-23.55483864547717,-46.650305919271126,-23.544053809299612,-46.637117325114225
8,6,8,10,1,12,4.3,24.84,-23.556186597324206,-46.5916453491551,-23.594367870438827,-46.58400413651125
8,6,8,8,1,10,3.9,22.27,-23.528081477096155,-46.66274574818299,-23.507963670019315,-46.631403553031575
7,5,8,10,1,12,4.3,24.82,-23.56190480466115,-46.59304482077118,-23.564145974224477,-46.550996340523426
6,4,8,17,2,13,4.7,26.21,-23.58952513523125,-46.6514476114351,-23.590481177975906,-46.69748206212741
6,4,8,15,2,8,2.8,18.62,-23.53896283804417,-46.60892062746685,-23.55802955563134,-46.590912390594156
5,3,8,18,2,6,2.4,21.58,-23.565649860996825,-46.61648091765579,-23.580508160270192,-46.63359425988376
4,2,8,18,2,11,4.3,24.48,-23.54392789139397,-46.67481221193208,-23.582561682000318,-46.67899260066639
4,2,8,13,2,9,2.7,18.3,-23.53396623825137,-46.61389807966803,-23.515657882788428,-46.596440090137946
4,2,8,13,2,9,2.7,18.3,-23.52704144956707,-46.64042954308985,-23.545796362281788,-46.6573222635159
4,2,8,10,1,9,3.4,20.7,-23.52282116107812,-46.61895291482005,-23.515213847742505,-46.651206661535596
4,2,8,8,1,18,5.3,29.0,-23.503111679312326,-46.62623618600637,-23.48175143985448,-46.57980554964485
2,7,8,16,2,9,4.2,24.99,-23.542537161690568,-46.67352238759091,-23.54752692355556,-46.714298373965
1,6,8,9,1,19,6.3,33.12,-23.604522232316928,-46.65270352606849,-23.623672877792462,-46.59457449263816
31,5,7,11,1,20,3.4,20.71,-23.58085160324119,-46.638448551152095,-23.611366929388144,-46.642088039112295
30,4,7,11,1,9,4.3,23.74,-23.58267511275595,-46.65691558310778,-23.619333845662368,-46.64303844751772
30,4,7,9,1,14,4.5,25.42,-23.59093235795775,-46.63787988744385,-23.55428991568699,-46.65692702017331
27,1,7,16,2,6,2.1,16.01,-23.568428560212695,-46.64006837558516,-23.549473816223248,-46.64060926299123
26,7,7,11,1,12,3.7,23.9,-23.55184803191988,-46.59710020977294,-23.55067116627592,-46.63331617231674
26,7,7,10,1,35,3.7,23.18,-23.54950531306466,-46.59708860588252,-23.54771916589823,-46.56090270622493
22,3,7,16,2,11,4.1,24.26,-23.565651295387273,-46.596659520570434,-23.596204692997198,-46.61933875107746
22,3,7,15,2,12,4.0,23.5,-23.57916971853328,-46.60945316956091,-23.60489940243788,-46.58195173121748
21,2,7,13,2,10,2.8,19.37,-23.575682019471067,-46.63597570399882,-23.55554344638493,-46.61939489370626
14,2,7,11,1,18,3.6,21.8,-23.550826330854978,-46.59805268541921,-23.582200587921303,-46.58883244115986
14,2,7,10,1,10,4.1,23.6,-23.544797353915868,-46.593637643871006,-23.52842010636264,-46.629646548273094
9,4,7,19,3,11,4.6,25.29,-23.514138230547946,-46.61157875140306,-23.472734048702197,-46.61514506715658
9,4,7,15,2,9,3.6,22.05,-23.52204504453654,-46.61630692028839,-23.51174169537111,-46.64973910292045
9,4,7,14,2,13,4.1,24.28,-23.52652919354431,-46.602730255951364,-23.542570472087785,-46.56654444323481
8,3,7,9,1,15,4.0,24.84,-23.514455511334003,-46.63541923653758,-23.5478815744922,-46.62058308527596
8,3,7,7,1,8,2.7,18.43,-23.55657499830227,-46.658926088068306,-23.57881770326615,-46.6480998946626
4,6,7,8,1,22,5.3,28.76,-23.589825474039763,-46.60369561232913,-23.634857472060258,-46.58612417739812
2,4,7,11,1,10,3.2,20.82,-23.552586823304654,-46.60204885292742,-23.524826637203404,-46.61073972259892
2,4,7,9,1,17,4.1,26.02,-23.55364199410588,-46.59329667818119,-23.586234337169646,-46.6123421594789
30,2,6,17,2,9,3.4,20.06,-23.522118348011013,-46.64594896593486,-23.51946791586195,-46.67911719030841
30,2,6,15,2,10,4.4,24.44,-23.58811198999901,-46.619366653643056,-23.627251978577924,-46.62675796941027
30,2,6,12,2,11,4.4,24.71,-23.51939474652983,-46.6600880300433,-23.524642656978823,-46.70279533996867
14,7,6,14,2,16,2.9,19.44,-23.544971286762944,-46.66106733723814,-23.530047785192153,-46.68440352615266
13,5,3,11,1,7,2.8,18.24,-23.538080164062002,-46.60943705428962,-23.55311135708937,-46.587387669051544
13,5,3,10,1,9,2.8,18.77,-23.575616460094924,-46.62999585489984,-23.55060194637042,-46.63397280569553
11,3,3,21,3,11,4.8,27.17,-23.586781033951983,-46.607557276230146,-23.62620994875934,-46.627081649586344
11,3,3,19,3,12,4.7,25.93,-23.550647064582982,-46.58727781035651,-23.51170362357291,-46.60556589772666
10,2,3,15,2,11,4.5,25.13,-23.56251712746057,-46.59119957653593,-23.57835325966051,-46.550605252771625
27,5,2,10,1,19,3.9,22.51,-23.518431156785947,-46.6175806058437,-23.50917367790593,-46.58073732330858
7,6,2,15,2,7,2.5,17.19,-23.56449817547081,-46.614083148799594,-23.554442748350525,-46.63600633481806
7,6,2,14,2,7,2.7,18.18,-23.572556569987853,-46.621999040973286,-23.588947580173706,-46.60241969297016
5,4,11,8,1,10,4.4,24.4,-23.533712554402747,-46.672355241231394,-23.50473499262177,-46.642881465278435
3,2,11,19,3,11,4.9,26.3,-23.565484414586976,-46.67847528533725,-23.55153142826075,-46.63293040482265
3,2,11,9,1,19,4.2,26.54,-23.51308482752438,-46.639884048647026,-23.512599617169542,-46.681004283528814
13,7,9,16,2,9,3.3,20.85,-23.548143102538678,-46.66552731345911,-23.57686270678551,-46.65691652152404
8,2,9,18,2,8,3.3,20.22,-23.53609428774393,-46.66158862662388,-23.561019328985,-46.67929835946983
16,3,9,16,2,6,2.7,17.6,-23.52709578982507,-46.640637087044894,-23.545399611582383,-46.65810214315245
18,5,9,16,2,11,3.8,22.57,-23.569343086466944,-46.60219073726002,-23.590506787128835,-46.5728901134786
23,3,9,11,1,7,3.6,20.89,-23.533576277470456,-46.60322216293021,-23.508441801330168,-46.58086920287663
23,3,9,15,2,6,3.2,20.42,-23.575975117559693,-46.64813938143347,-23.547123040531613,-46.64646361035985
4,7,10,7,1,8,4.2,24.5,-23.578337409459653,-46.605349224311325,-23.60218129790673,-46.63734584840797
10,6,10,13,2,13,5.4,28.42,-23.515410374556044,-46.59661630758992,-23.478865884603117,-46.631614012401144
10,6,10,16,2,16,3.9,22.83,-23.5213554843025,-46.611905989534826,-23.503239661964802,-46.64465133213327
14,3,10,11,1,8,4.1,22.89,-23.571228690288653,-46.666597831824966,-23.60812056217334,-46.66326481008977
17,6,10,8,1,11,4.2,23.64,-23.58842908643452,-46.63440621029408,-23.594936452414483,-46.674944007290996
17,6,10,11,1,13,5.1,27.39,-23.51531696096904,-46.60111345890479,-23.55151399000115,-46.57024046565555
20,2,10,14,2,7,3.9,20.89,-23.517264011398023,-46.645867801877856,-23.516109512359918,-46.60770102096872
23,5,10,10,1,11,4.1,23.22,-23.529690602716872,-46.600116087539234,-23.560056810140576,-46.57714886305721
24,6,10,9,1,10,4.5,24.5,-23.590523212050687,-46.6410306405641,-23.553727529153193,-46.65972676773843
24,6,10,22,3,8,3.9,22.05,-23.525886953999475,-46.66060338245197,-23.501591898245998,-46.63296093803911
29,4,10,8,1,10,4.4,24.32,-23.590041552054057,-46.62891773408516,-23.557223743453584,-46.604626071422814
29,4,10,11,1,6,2.7,17.75,-23.54297872716528,-46.65845639652288,-23.51884080822855,-46.654747955606
31,6,10,9,1,16,4.4,25.44,-23.573678700416504,-46.6683281668416,-23.535632094284058,-46.68073453379338
31,6,10,11,1,9,4.1,23.2,-23.560904633312603,-46.59476487577421,-23.566345565251257,-46.555041115760474
31,6,10,18,2,12,4.4,24.97,-23.527357145159225,-46.66831885283736,-23.496493048185922,-46.695445534949584
31,6,10,19,3,11,4.0,22.76,-23.546997052088862,-46.67229914777425,-23.582654490207865,-46.678527820987235
3,2,11,8,1,19,4.2,26.54,-23.515942394764185,-46.65020018693508,-23.544022568520926,-46.67784307625833
3,2,11,19,3,11,4.9,26.3,-23.58482790835687,-46.66361642769025,-23.54243060423501,-46.67733475490501
3,2,11,19,3,11,4.9,26.3,-23.57970738126003,-46.59723949757959,-23.62364393523565,-46.59160051732663

In [0]:
!pip install haversine

Collecting haversine
  Downloading haversine-2.9.0-py2.py3-none-any.whl.metadata (5.8 kB)
Downloading haversine-2.9.0-py2.py3-none-any.whl (7.7 kB)
Installing collected packages: haversine
Successfully installed haversine-2.9.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
%restart_python

In [0]:
from haversine import haversine
from pyspark.sql.types import FloatType

def dist_haversine(lat_o, lon_o, lat_d, lon_d):
    return haversine((lat_o, lon_o), (lat_d, lon_d))

spark.udf.register("dist_haversine", dist_haversine, FloatType())

In [0]:
%sql

SELECT 
  dist_haversine(latitude_origem, longitude_origem, latitude_destino, longitude_destino) as distancia
FROM sandbox.prcg.transacoes LIMIT 5

distancia
4.2078524
4.3162794
4.215667
3.4003665
3.5976384

In [0]:

spark.sql("""
    WITH tbl_features AS (
    SELECT 
        day(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as dia,
        dayofweek(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as dia_semana,
        month(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as mes,
        hour(to_timestamp(datahora_entregue, 'dd/MM/yyy HH:mm')) as hora,
        duracao,
        vlr_pago,
        latitude_origem,
        longitude_origem,
        latitude_destino,
        longitude_destino
    FROM sandbox.prcg.transacoes
    )
    SELECT 
    dia,
    dia_semana,
    mes,
    hora,
    case when hora < 12 and hora > 6 then 1
        when hora >= 12 and hora <= 18 then 2
        else 3 end as periodo,
    duracao,
    vlr_pago,
    latitude_origem,
    longitude_origem,
    latitude_destino,
    longitude_destino,
    dist_haversine(latitude_origem, longitude_origem, latitude_destino, longitude_destino) as distancia
    FROM tbl_features
""").createOrReplaceTempView("tbl_features")

In [0]:
spark.sql(
    """
    SELECT 
        vlr_pago,
        dia,
        dia_semana,
        mes,
        hora,
        periodo,
        distancia,
        latitude_origem,
        longitude_origem,
        latitude_destino,
        longitude_destino
    FROM tbl_features
"""
).createOrReplaceTempView("tbl_ml")

In [0]:
spark.sql(
    """
    SELECT 
        vlr_pago,
        dia,
        dia_semana,
        mes,
        hora,
        periodo,
        distancia,
        duracao
    FROM tbl_features
"""
).createOrReplaceTempView("tbl_eda")

In [0]:
df_eda = spark.table("tbl_eda").toPandas()
df_ml = spark.table("tbl_ml").toPandas()

In [0]:
df_eda.describe().T

            count       mean        std  ...        50%       75%         max
vlr_pago    104.0  22.817692   3.371668  ...  23.330000  24.84250   33.120000
dia         104.0  14.567308   9.321407  ...  13.000000  23.00000   31.000000
dia_semana  104.0   4.269231   1.807378  ...   4.000000   6.00000    7.000000
mes         104.0   8.182692   2.079789  ...   8.000000  10.00000   11.000000
hora        104.0  12.990385   3.674882  ...  13.000000  16.00000   22.000000
periodo     104.0   1.634615   0.639443  ...   2.000000   2.00000    3.000000
distancia   104.0   3.849774   0.863909  ...   4.054581   4.39638    6.293622
duracao     104.0  12.211538  10.319811  ...  11.000000  13.00000  106.000000

[8 rows x 8 columns]

In [0]:
df_ml.describe().T

                   count       mean       std  ...        50%        75%        max
vlr_pago           104.0  22.817692  3.371668  ...  23.330000  24.842500  33.120000
dia                104.0  14.567308  9.321407  ...  13.000000  23.000000  31.000000
dia_semana         104.0   4.269231  1.807378  ...   4.000000   6.000000   7.000000
mes                104.0   8.182692  2.079789  ...   8.000000  10.000000  11.000000
hora               104.0  12.990385  3.674882  ...  13.000000  16.000000  22.000000
periodo            104.0   1.634615  0.639443  ...   2.000000   2.000000   3.000000
distancia          104.0   3.849774  0.863909  ...   4.054581   4.396380   6.293622
latitude_origem    104.0 -23.552737  0.026101  ... -23.552217 -23.529123 -23.503112
longitude_origem   104.0 -46.632568  0.026360  ... -46.634099 -46.608650 -46.587278
latitude_destino   104.0 -23.552667  0.040540  ... -23.550637 -23.519311 -23.472734
longitude_destino  104.0 -46.633031  0.037944  ... -46.635897 -46.605331 -46.550605

[11 rows x 8 columns]

In [0]:
df_eda[df_eda["duracao"] > 100]

   vlr_pago  dia  dia_semana  mes  hora  periodo  distancia  duracao
7      27.0   10           6   10    19        3   4.918842      106